Improve crane agent doc
gocrane/crane pull request #417
Opened 2022-07-17 04:08 UTC by chenkaiyue

#### What type of PR is this?
Documentation

#### What this PR does / why we need it:
Improve Crane agent's doc

2022-07-18 03:22 UTC, qmhu reviewed
Better to make sure document format is consistence with others like: https://github.com/gocrane/crane/blob/main/docs/tutorials/using-effective-hpa-to-scaling-with-effectiveness.zh.md

It's more effective to have some overall summary for Entire QoS features in the documents.

2022-07-18 07:21 UTC, zsnmwy requested changes
Please fix these.

2022-07-18 07:21 UTC, zsnmwy commented on docs/tutorials/using-qos-ensurance.md
> +   ```
Please remove the blank.

<img width="826" alt="image" src="https://user-images.githubusercontent.com/35299017/179460200-88c53e0a-2ce8-4425-aa80-340a53cba77d.png">

2022-07-18 07:21 UTC, zsnmwy commented on docs/tutorials/using-qos-ensurance.md
> +- None: select the CPU that is not occupied by the container of exclusive pod, can use the binding core of share type
```suggestion
1. Three types of pod cpuset are provided:

- Exclusive: after binding the core, other containers can no longer use the CPU and monopolize the CPU
- Share: other containers can use the CPU after binding the core
- None: select the CPU that is not occupied by the container of exclusive pod, can use the binding core of share type
```

Add a new line to make sure the list style works.

2022-07-18 07:21 UTC, zsnmwy commented on docs/tutorials/using-qos-ensurance.md
> +When deploying pod, limit and request use gocrane.io/<$resourcename>:<$value>, as follows
```suggestion
When deploying pod, limit and request use `gocrane.io/<$resourcename>:<$value>`, as follows
```

2022-07-18 07:21 UTC, zsnmwy commented on docs/tutorials/using-qos-ensurance.md
> +When deploying pod, limit and request use gocrane.io/<$resourcename>:<$value>
```suggestion
When deploying pod, limit and request use `gocrane.io/<$resourcename>:<$value>`
```

2022-07-18 07:21 UTC, zsnmwy commented on docs/tutorials/using-qos-ensurance.zh.md
> +- none：选择没有被exclusive pod的container占用的cpu，可以使用share类型的绑核
```suggestion
1. 提供了3种pod cpuset类型：

- exclusive：绑核后其他container不能再使用该cpu，独占cpu
- share：绑核后其他container可以使用该cpu
- none：选择没有被exclusive pod的container占用的cpu，可以使用share类型的绑核
```

2022-07-18 07:21 UTC, zsnmwy commented on docs/tutorials/using-qos-ensurance.zh.md
> +    pod的cpu manager policy从none转换到share，从exclusive转换到share，均无需重启
Fix the list style.

<img width="829" alt="image" src="https://user-images.githubusercontent.com/35299017/179461558-058a4cf9-77f1-4132-b8f0-b9c8a93f704b.png">

2022-07-18 07:21 UTC, zsnmwy commented on docs/tutorials/using-qos-ensurance.zh.md
> +1. 通过本地收集的cpu用量信息
```suggestion
crane通过如下两种方式收集了节点的空闲资源量，综合后作为节点的空闲资源量，增强了资源评估的准确性：

1. 通过本地收集的cpu用量信息  
```

2022-07-18 07:21 UTC, zsnmwy commented on docs/tutorials/using-qos-ensurance.zh.md
> +部署pod时limit和request使用gocrane.io/<$ResourceName>：<$value>即可，如下
```suggestion
部署pod时limit和request使用`gocrane.io/<$ResourceName>:<$value>`即可，如下
```

2022-07-18 07:21 UTC, zsnmwy commented on docs/tutorials/using-qos-ensurance.zh.md
> +部署pod时limit和request使用gocrane.io/<$ResourceName>：<$value>即可
```suggestion
部署pod时limit和request使用`gocrane.io/<$ResourceName>:<$value>`即可
```

2022-08-05 09:24 UTC, qmhu approved these changes

2022-08-05 09:25 UTC, merged