update 2022 roadmap
gocrane/crane pull request #431
Opened 2022-07-27 09:47 UTC by mfanjie

#### What type of PR is this?
Doc
#### What this PR does / why we need it:
Roadmap of 2022(H2)
#### Special notes for your reviewer:

2022-07-27 11:15 UTC, qmhu commented on docs/roadmaps/roadmap-2022.md
> +- Recommendation Framework
- Support APIService router for multiple metric adapters
is replaced by `Support remote adapter for external metric` and released in 0.6.0
- Prediction with business metrics
is released in 0.6.0

2022-07-27 11:20 UTC, xieydd requested changes

2022-07-27 11:20 UTC, xieydd commented on docs/roadmaps/roadmap-2022.md
> +- Internal recommendation plugins
Internal -> External

2022-07-28 11:10 UTC, qmhu commented
/LGTM

2022-07-28 11:10 UTC, qmhu approved these changes

2022-07-28 11:17 UTC, xieydd commented
/LGTM

2022-07-28 11:26 UTC, xieydd approved these changes

2022-07-28 11:29 UTC, merged