Add prometheus api
gocrane/crane pull request #439
Opened 2022-07-27 12:10 UTC by qmhu

#### What type of PR is this?

Add prometheus api

#### What this PR does / why we need it:

Add prometheus api for crane server

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

2022-07-27 15:33 UTC, ClouderPing approved these changes

2022-07-28 01:36 UTC, zsnmwy requested changes

2022-07-28 01:36 UTC, zsnmwy commented on pkg/server/handler/prometheus/prometheus.go
> +	ts, err := time.Parse("2006-01-02 15:04:05", c.Query("time"))
Please change to Unix timestamp.
Avoid the timezone issues.

2022-07-28 01:36 UTC, zsnmwy commented on pkg/server/handler/prometheus/prometheus.go
> +	tsStart, err := time.Parse("2006-01-02 15:04:05", c.Query("start"))
Please change to Unix timestamp.
Avoid the timezone issues.

2022-07-28 04:09 UTC, zsnmwy requested changes

2022-07-28 04:09 UTC, zsnmwy commented on pkg/utils/time.go
> +	i, err := strconv.ParseInt("ts", 10, 64)
```suggestion
func ParseTimestamp(ts string) (time.Time, error) {
	i, err := strconv.ParseInt(ts, 10, 64)
```

2022-07-28 10:47 UTC, merged