Fixed issue #459
gocrane/crane pull request #499
Opened 2022-08-19 13:04 UTC by YashPimple

#### What type of PR is this?

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

2022-08-20 13:00 UTC, zsnmwy commented
The developer guide seems not complete.

I have some advice for you.

The developer guide should focus on how to dev based on the developer. 
The guide doesn't need to describe how to install Crane in detail, just a [paste link ](https://docs.gocrane.io/dev/installation/#steps)is enough.

We should focus on these tasks and describe them in detail:
- How to build binary and images from code
   https://github.com/gocrane/crane/blob/702aa9c78327840b494c837674f9478b9bef8049/Makefile#L103-L165
- How to prepare local environments
   - go version
   - application bootstrap
   - the local application connects to the remote k8s cluster.
   - application debug

2022-08-20 13:01 UTC, zsnmwy requested changes

2022-08-20 13:01 UTC, zsnmwy commented on Developer-Guide.md
> +```
The guide doesn't need to describe how to install Crane in detail, just a [paste link ](https://docs.gocrane.io/dev/installation/#steps)is enough.

2022-11-07 11:15 UTC, closed without merging

2022-11-07 11:16 UTC, qmhu commented
Develop Guide is already contains these content.